# Form implementation generated from reading ui file 'Frm_ChangePassword.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_ChangePassword(object):
    def setupUi(self, Frm_ChangePassword):
        Frm_ChangePassword.setObjectName("Frm_ChangePassword")
        Frm_ChangePassword.resize(350, 284)
        self.label = QtWidgets.QLabel(parent=Frm_ChangePassword)
        self.label.setGeometry(QtCore.QRect(30, 40, 71, 16))
        self.label.setObjectName("label")
        self.btn_Clear = QtWidgets.QPushButton(parent=Frm_ChangePassword)
        self.btn_Clear.setGeometry(QtCore.QRect(190, 210, 91, 31))
        self.btn_Clear.setObjectName("btn_Clear")
        self.txt_OldPwd = QtWidgets.QLineEdit(parent=Frm_ChangePassword)
        self.txt_OldPwd.setGeometry(QtCore.QRect(110, 80, 191, 20))
        self.txt_OldPwd.setText("")
        self.txt_OldPwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_OldPwd.setPlaceholderText("")
        self.txt_OldPwd.setObjectName("txt_OldPwd")
        self.txt_UserName = QtWidgets.QLineEdit(parent=Frm_ChangePassword)
        self.txt_UserName.setGeometry(QtCore.QRect(110, 40, 191, 20))
        self.txt_UserName.setStyleSheet("background-color:rgb(242, 245, 255)")
        self.txt_UserName.setText("")
        self.txt_UserName.setObjectName("txt_UserName")
        self.label_2 = QtWidgets.QLabel(parent=Frm_ChangePassword)
        self.label_2.setGeometry(QtCore.QRect(42, 83, 61, 16))
        self.label_2.setObjectName("label_2")
        self.btn_Save = QtWidgets.QPushButton(parent=Frm_ChangePassword)
        self.btn_Save.setGeometry(QtCore.QRect(40, 210, 91, 31))
        self.btn_Save.setObjectName("btn_Save")
        self.txt_NewPwd1 = QtWidgets.QLineEdit(parent=Frm_ChangePassword)
        self.txt_NewPwd1.setGeometry(QtCore.QRect(108, 117, 191, 20))
        self.txt_NewPwd1.setText("")
        self.txt_NewPwd1.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_NewPwd1.setPlaceholderText("")
        self.txt_NewPwd1.setObjectName("txt_NewPwd1")
        self.label_3 = QtWidgets.QLabel(parent=Frm_ChangePassword)
        self.label_3.setGeometry(QtCore.QRect(54, 120, 51, 16))
        self.label_3.setObjectName("label_3")
        self.txt_NewPwd2 = QtWidgets.QLineEdit(parent=Frm_ChangePassword)
        self.txt_NewPwd2.setGeometry(QtCore.QRect(108, 157, 191, 20))
        self.txt_NewPwd2.setText("")
        self.txt_NewPwd2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_NewPwd2.setPlaceholderText("")
        self.txt_NewPwd2.setObjectName("txt_NewPwd2")
        self.label_4 = QtWidgets.QLabel(parent=Frm_ChangePassword)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Frm_ChangePassword)
        self.label_5.setGeometry(QtCore.QRect(304, 84, 21, 16))
        self.label_5.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Frm_ChangePassword)
        self.label_6.setGeometry(QtCore.QRect(303, 120, 21, 16))
        self.label_6.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Frm_ChangePassword)
        self.label_7.setGeometry(QtCore.QRect(304, 161, 21, 16))
        self.label_7.setStyleSheet("color:rgb(255, 0, 0)")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Frm_ChangePassword)
        QtCore.QMetaObject.connectSlotsByName(Frm_ChangePassword)
        Frm_ChangePassword.setTabOrder(self.txt_OldPwd, self.txt_NewPwd1)
        Frm_ChangePassword.setTabOrder(self.txt_NewPwd1, self.txt_NewPwd2)
        Frm_ChangePassword.setTabOrder(self.txt_NewPwd2, self.btn_Save)
        Frm_ChangePassword.setTabOrder(self.btn_Save, self.btn_Clear)
        Frm_ChangePassword.setTabOrder(self.btn_Clear, self.txt_UserName)

    def retranslateUi(self, Frm_ChangePassword):
        _translate = QtCore.QCoreApplication.translate
        Frm_ChangePassword.setWindowTitle(_translate("Frm_ChangePassword", "修改密码"))
        self.label.setText(_translate("Frm_ChangePassword", "当前用户名："))
        self.btn_Clear.setText(_translate("Frm_ChangePassword", "清  空"))
        self.label_2.setText(_translate("Frm_ChangePassword", "当前密码："))
        self.btn_Save.setText(_translate("Frm_ChangePassword", "修改密码"))
        self.label_3.setText(_translate("Frm_ChangePassword", "新密码："))
        self.label_4.setText(_translate("Frm_ChangePassword", "确认密码："))
        self.label_5.setText(_translate("Frm_ChangePassword", "(*)"))
        self.label_6.setText(_translate("Frm_ChangePassword", "(*)"))
        self.label_7.setText(_translate("Frm_ChangePassword", "(*)"))
