# Form implementation generated from reading ui file 'Frm_Target_UCC_M.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_Target_UCC_M(object):
    def setupUi(self, Frm_Target_UCC_M):
        Frm_Target_UCC_M.setObjectName("Frm_Target_UCC_M")
        Frm_Target_UCC_M.resize(801, 589)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frm_Target_UCC_M.sizePolicy().hasHeightForWidth())
        Frm_Target_UCC_M.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Frm_Target_UCC_M)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(parent=Frm_Target_UCC_M)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_export = QtWidgets.QPushButton(parent=Frm_Target_UCC_M)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_export.sizePolicy().hasHeightForWidth())
        self.btn_export.setSizePolicy(sizePolicy)
        self.btn_export.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tb_dan = QtWidgets.QTableView(parent=Frm_Target_UCC_M)
        self.tb_dan.setMinimumSize(QtCore.QSize(781, 521))
        self.tb_dan.setObjectName("tb_dan")
        self.verticalLayout.addWidget(self.tb_dan)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Frm_Target_UCC_M)
        QtCore.QMetaObject.connectSlotsByName(Frm_Target_UCC_M)

    def retranslateUi(self, Frm_Target_UCC_M):
        _translate = QtCore.QCoreApplication.translate
        Frm_Target_UCC_M.setWindowTitle(_translate("Frm_Target_UCC_M", "地下指挥所数据模型管理"))
        self.btn_add.setText(_translate("Frm_Target_UCC_M", "添加地下指挥所数据模型"))
        self.btn_export.setText(_translate("Frm_Target_UCC_M", "导出地下指挥所数据模型"))
