# Form implementation generated from reading ui file 'Frm_PG_AssessmentReport.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_PG_AssessmentReport(object):
    def setupUi(self, Frm_PG_AssessmentReport):
        Frm_PG_AssessmentReport.setObjectName("Frm_PG_AssessmentReport")
        Frm_PG_AssessmentReport.resize(1200, 750)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frm_PG_AssessmentReport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.btn_add = QtWidgets.QPushButton(parent=Frm_PG_AssessmentReport)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_buttons.addWidget(self.btn_add)
        self.btn_export = QtWidgets.QPushButton(parent=Frm_PG_AssessmentReport)
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout_buttons.addWidget(self.btn_export)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)
        self.tb_assessment_report = QtWidgets.QTableView(parent=Frm_PG_AssessmentReport)
        self.tb_assessment_report.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tb_assessment_report.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tb_assessment_report.setObjectName("tb_assessment_report")
        self.verticalLayout.addWidget(self.tb_assessment_report)

        self.retranslateUi(Frm_PG_AssessmentReport)
        QtCore.QMetaObject.connectSlotsByName(Frm_PG_AssessmentReport)

    def retranslateUi(self, Frm_PG_AssessmentReport):
        _translate = QtCore.QCoreApplication.translate
        Frm_PG_AssessmentReport.setWindowTitle(_translate("Frm_PG_AssessmentReport", "毁伤评估报告管理"))
        self.btn_add.setText(_translate("Frm_PG_AssessmentReport", "添加"))
        self.btn_export.setText(_translate("Frm_PG_AssessmentReport", "导出"))
