# Form implementation generated from reading ui file 'Frm_PG_DamageScene.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_PG_DamageScene(object):
    def setupUi(self, Frm_PG_DamageScene):
        Frm_PG_DamageScene.setObjectName("Frm_PG_DamageScene")
        Frm_PG_DamageScene.resize(1000, 650)
        self.gridLayout = QtWidgets.QGridLayout(Frm_PG_DamageScene)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(parent=Frm_PG_DamageScene)
        self.btn_add.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_export = QtWidgets.QPushButton(parent=Frm_PG_DamageScene)
        self.btn_export.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tb_damage_scene = QtWidgets.QTableView(parent=Frm_PG_DamageScene)
        self.tb_damage_scene.setMinimumSize(QtCore.QSize(980, 580))
        self.tb_damage_scene.setObjectName("tb_damage_scene")
        self.verticalLayout.addWidget(self.tb_damage_scene)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Frm_PG_DamageScene)
        QtCore.QMetaObject.connectSlotsByName(Frm_PG_DamageScene)

    def retranslateUi(self, Frm_PG_DamageScene):
        _translate = QtCore.QCoreApplication.translate
        Frm_PG_DamageScene.setWindowTitle(_translate("Frm_PG_DamageScene", "毁伤场景设置"))
        self.btn_add.setText(_translate("Frm_PG_DamageScene", "添加"))
        self.btn_export.setText(_translate("Frm_PG_DamageScene", "导出"))
