# Form implementation generated from reading ui file 'Frm_UndergroundModelManagement.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_UndergroundModelManagement(object):
    def setupUi(self, Frm_UndergroundModelManagement):
        Frm_UndergroundModelManagement.setObjectName("Frm_UndergroundModelManagement")
        Frm_UndergroundModelManagement.resize(801, 589)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frm_UndergroundModelManagement.sizePolicy().hasHeightForWidth())
        Frm_UndergroundModelManagement.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Frm_UndergroundModelManagement)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(parent=Frm_UndergroundModelManagement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_export = QtWidgets.QPushButton(parent=Frm_UndergroundModelManagement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_export.sizePolicy().hasHeightForWidth())
        self.btn_export.setSizePolicy(sizePolicy)
        self.btn_export.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tb_dan = QtWidgets.QTableView(parent=Frm_UndergroundModelManagement)
        self.tb_dan.setMinimumSize(QtCore.QSize(781, 521))
        self.tb_dan.setObjectName("tb_dan")
        self.verticalLayout.addWidget(self.tb_dan)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Frm_UndergroundModelManagement)
        QtCore.QMetaObject.connectSlotsByName(Frm_UndergroundModelManagement)

    def retranslateUi(self, Frm_UndergroundModelManagement):
        _translate = QtCore.QCoreApplication.translate
        Frm_UndergroundModelManagement.setWindowTitle(_translate("Frm_UndergroundModelManagement", "地下指挥所数据模型管理"))
        self.btn_add.setText(_translate("Frm_UndergroundModelManagement", "添加地下指挥所数据模型"))
        self.btn_export.setText(_translate("Frm_UndergroundModelManagement", "导出地下指挥所数据模型"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frm_UndergroundModelManagement = QtWidgets.QWidget()
    ui = Ui_Frm_UndergroundModelManagement()
    ui.setupUi(Frm_UndergroundModelManagement)
    Frm_UndergroundModelManagement.show()
    sys.exit(app.exec())
