# Form implementation generated from reading ui file 'Frm_Ammunition_M.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_AmmunitionManagement(object):
    def setupUi(self, Frm_AmmunitionManagement):
        Frm_AmmunitionManagement.setObjectName("Frm_AmmunitionManagement")
        Frm_AmmunitionManagement.resize(793, 594)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frm_AmmunitionManagement.sizePolicy().hasHeightForWidth())
        Frm_AmmunitionManagement.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frm_AmmunitionManagement)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tb_dan = QtWidgets.QTableView(parent=Frm_AmmunitionManagement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tb_dan.sizePolicy().hasHeightForWidth())
        self.tb_dan.setSizePolicy(sizePolicy)
        self.tb_dan.setMinimumSize(QtCore.QSize(0, 0))
        self.tb_dan.setObjectName("tb_dan")
        self.gridLayout_2.addWidget(self.tb_dan, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_add = QtWidgets.QPushButton(parent=Frm_AmmunitionManagement)
        self.btn_add.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_add.setAutoDefault(False)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 0, 0, 1, 1)
        self.btn_export = QtWidgets.QPushButton(parent=Frm_AmmunitionManagement)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_export.sizePolicy().hasHeightForWidth())
        self.btn_export.setSizePolicy(sizePolicy)
        self.btn_export.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_export.setObjectName("btn_export")
        self.gridLayout.addWidget(self.btn_export, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(397, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Frm_AmmunitionManagement)
        QtCore.QMetaObject.connectSlotsByName(Frm_AmmunitionManagement)

    def retranslateUi(self, Frm_AmmunitionManagement):
        _translate = QtCore.QCoreApplication.translate
        self.btn_add.setText(_translate("Frm_AmmunitionManagement", "添加弹药毁伤数据"))
        self.btn_export.setText(_translate("Frm_AmmunitionManagement", "导出弹药毁伤数据"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frm_AmmunitionManagement = QtWidgets.QDialog()
    ui = Ui_Frm_AmmunitionManagement()
    ui.setupUi(Frm_AmmunitionManagement)
    Frm_AmmunitionManagement.show()
    sys.exit(app.exec())
