# Form implementation generated from reading ui file 'Frm_PG_AssessmentResult.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_PG_AssessmentResult(object):
    def setupUi(self, Frm_PG_AssessmentResult):
        Frm_PG_AssessmentResult.setObjectName("Frm_PG_AssessmentResult")
        Frm_PG_AssessmentResult.resize(1200, 750)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frm_PG_AssessmentResult)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.btn_add = QtWidgets.QPushButton(parent=Frm_PG_AssessmentResult)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_buttons.addWidget(self.btn_add)
        self.btn_export = QtWidgets.QPushButton(parent=Frm_PG_AssessmentResult)
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout_buttons.addWidget(self.btn_export)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)
        self.tb_assessment_result = QtWidgets.QTableView(parent=Frm_PG_AssessmentResult)
        self.tb_assessment_result.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tb_assessment_result.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tb_assessment_result.setObjectName("tb_assessment_result")
        self.verticalLayout.addWidget(self.tb_assessment_result)

        self.retranslateUi(Frm_PG_AssessmentResult)
        QtCore.QMetaObject.connectSlotsByName(Frm_PG_AssessmentResult)

    def retranslateUi(self, Frm_PG_AssessmentResult):
        _translate = QtCore.QCoreApplication.translate
        Frm_PG_AssessmentResult.setWindowTitle(_translate("Frm_PG_AssessmentResult", "毁伤能力计算"))
        self.btn_add.setText(_translate("Frm_PG_AssessmentResult", "添加"))
        self.btn_export.setText(_translate("Frm_PG_AssessmentResult", "导出"))
