# Form implementation generated from reading ui file 'Frm_ObjectiveManagement.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_ObjectiveManagement(object):
    def setupUi(self, Frm_ObjectiveManagement):
        Frm_ObjectiveManagement.setObjectName("Frm_ObjectiveManagement")
        Frm_ObjectiveManagement.resize(764, 496)
        self.pushButton = QtWidgets.QPushButton(parent=Frm_ObjectiveManagement)
        self.pushButton.setGeometry(QtCore.QRect(160, 300, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Frm_ObjectiveManagement)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 300, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Frm_ObjectiveManagement)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 300, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableView = QtWidgets.QTableView(parent=Frm_ObjectiveManagement)
        self.tableView.setGeometry(QtCore.QRect(150, 40, 256, 192))
        self.tableView.setObjectName("tableView")
        self.groupBox = QtWidgets.QGroupBox(parent=Frm_ObjectiveManagement)
        self.groupBox.setGeometry(QtCore.QRect(440, 30, 281, 221))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(100, 80, 113, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Frm_ObjectiveManagement)
        QtCore.QMetaObject.connectSlotsByName(Frm_ObjectiveManagement)

    def retranslateUi(self, Frm_ObjectiveManagement):
        _translate = QtCore.QCoreApplication.translate
        Frm_ObjectiveManagement.setWindowTitle(_translate("Frm_ObjectiveManagement", "Form"))
        self.pushButton.setText(_translate("Frm_ObjectiveManagement", "PushButton"))
        self.pushButton_2.setText(_translate("Frm_ObjectiveManagement", "PushButton"))
        self.pushButton_3.setText(_translate("Frm_ObjectiveManagement", "PushButton"))
        self.groupBox.setTitle(_translate("Frm_ObjectiveManagement", "GroupBox"))
