# Form implementation generated from reading ui file 'Frm_Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frm_Login(object):
    def setupUi(self, Frm_Login):
        Frm_Login.setObjectName("Frm_Login")
        Frm_Login.resize(400, 300)
        self.btn_Login = QtWidgets.QPushButton(parent=Frm_Login)
        self.btn_Login.setGeometry(QtCore.QRect(70, 210, 91, 31))
        self.btn_Login.setObjectName("btn_Login")
        self.label = QtWidgets.QLabel(parent=Frm_Login)
        self.label.setGeometry(QtCore.QRect(80, 130, 54, 16))
        self.label.setObjectName("label")
        self.txt_UserName = QtWidgets.QLineEdit(parent=Frm_Login)
        self.txt_UserName.setGeometry(QtCore.QRect(140, 130, 191, 20))
        self.txt_UserName.setObjectName("txt_UserName")
        self.label_2 = QtWidgets.QLabel(parent=Frm_Login)
        self.label_2.setGeometry(QtCore.QRect(80, 173, 54, 16))
        self.label_2.setObjectName("label_2")
        self.txt_Pwd = QtWidgets.QLineEdit(parent=Frm_Login)
        self.txt_Pwd.setGeometry(QtCore.QRect(140, 170, 191, 20))
        self.txt_Pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_Pwd.setPlaceholderText("")
        self.txt_Pwd.setObjectName("txt_Pwd")
        self.btn_Clear = QtWidgets.QPushButton(parent=Frm_Login)
        self.btn_Clear.setGeometry(QtCore.QRect(220, 210, 91, 31))
        self.btn_Clear.setObjectName("btn_Clear")
        self.lbl_bg = QtWidgets.QLabel(parent=Frm_Login)
        self.lbl_bg.setGeometry(QtCore.QRect(0, 0, 401, 111))
        self.lbl_bg.setObjectName("lbl_bg")

        self.retranslateUi(Frm_Login)
        QtCore.QMetaObject.connectSlotsByName(Frm_Login)
        Frm_Login.setTabOrder(self.txt_UserName, self.txt_Pwd)
        Frm_Login.setTabOrder(self.txt_Pwd, self.btn_Login)
        Frm_Login.setTabOrder(self.btn_Login, self.btn_Clear)

    def retranslateUi(self, Frm_Login):
        _translate = QtCore.QCoreApplication.translate
        Frm_Login.setWindowTitle(_translate("Frm_Login", "系统登录"))
        self.btn_Login.setText(_translate("Frm_Login", "登  录"))
        self.label.setText(_translate("Frm_Login", "用户名："))
        self.txt_UserName.setText(_translate("Frm_Login", "admin"))
        self.label_2.setText(_translate("Frm_Login", "密  码："))
        self.txt_Pwd.setText(_translate("Frm_Login", "123456"))
        self.btn_Clear.setText(_translate("Frm_Login", "清  空"))
        self.lbl_bg.setText(_translate("Frm_Login", "TextLabel"))
